/** Multi-Dimensional Array with Indexes */
const arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [[10, 11, 12], 13, 14]
  ];
  
  console.log(arr[3]); //print the third value element
  console.log(arr[3][0]); // print the first of the third element
  console.log(arr[3][0][1]); 


/** Mult-dimensional array*/

const x = [[2,3,4],[1,1,1],["Apple","Banana"]];
console.log(x[2]); // print fruits
